// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qteuofblpwewhzdfaakn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF0ZXVvZmJscHdld2h6ZGZhYWtuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5MDUyNjgsImV4cCI6MjA2ODQ4MTI2OH0.GCjZcdRWqeOGfx2fHrfSbpacGLfAD9NTIiSUdqPSY_8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});